### PR TITLE
Update markdown_deux_tags.py (import "force_text")

### PR DESCRIPTION
**Pull request by melkon98**

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
Looks good to me.  Thanks for doing this!

@trentm Your review please.

**Comment by maxmalysh** [comment]
Thanks for the PR! I guess this will fix https://github.com/trentm/django-markdown-deux/issues/35? 
@trentm could you merge this, please?

**Comment by to-bee** [comment]
Any news on when this will be merged? Thanks in advance.

**Comment by cclauss** [comment]
@trentm Would you be willing to add some other [contributor](https://github.com/trentm/django-markdown-deux/graphs/contributors) as a maintainer of this repo so that essential maintenance can be done?

An alternative would be to [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) this repo and direct visitors to an alternate solution such as  [django-markdownify](https://github.com/erwinmatijsen/django-markdownify).

**Comment by xrmx** [comment]
Merged, thanks!

**Pull request merged**
